params:
  optimizer: GradientDescentOptimizer
  learning_rate: 0.3
  clip_gradients: 5.0
  decay_type: exponential_decay
  decay_params:
    decay_rate: 0.7
    decay_steps: 100000
  start_decay_steps: 0

#  optimizer: AdamOptimizer
#  learning_rate: 1.0 # The scale constant.
#  clip_gradients: null
#  decay_step_duration: 8 # 1 decay step is 8 training steps.
#  decay_type: noam_decay_v2
#  decay_params:
#    model_dim: 512
#    warmup_steps: 2000 # (= 16000 training steps).
#  start_decay_steps: 0

  beam_width: 5
  maximum_iterations: 250

train:
  batch_size: 4
  bucket_width: 1
  save_checkpoints_steps: 5000
  keep_checkpoint_max: 0
  save_summary_steps: 50
  train_steps: 200000
  maximum_features_length: 500
  maximum_labels_length: 10

  # Consider setting this to -1 to match the number of training examples.
  sample_buffer_size: 0

eval:
  eval_delay: 3600  # Every 1 hour

infer:
  batch_size: 3
